# Generated by Django 5.0.3 on 2024-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
